options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'node:20'
    entrypoint: bash
    args:
      - -c
      - |
        npm install
        npm run build

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - app
      - deploy
      - '--version=$_VERSION'
      - '--quiet'
