steps:
  - name: 'node:20'
    entrypoint: bash
    args:
      - -c
      - |
        npm install
        npm run build

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - app
      - deploy
      - '--version=${SHORT_SHA}'
      - '--quiet'
substitutions:
  SHORT_SHA: ${COMMIT_SHA:0:8}
options:
  logging: CLOUD_LOGGING_ONLY